pipeline {
    
    agent any
    
    environment {
  EC2_IP = "44.216.122.26"
    }
  stages 
  {
  stage('checkout code')
  {
    steps 
    {
      git branch = "main",
      credientialId = "mern-stacks09233git",
      url = "https://github.com/kaviyarashugayu1997-maker/fullstack_project.git"
    }
  }
stage('build') {
  steps {
      script
      {
          sh 'docker build -t image .'
      }
    
  }
}
}
