pipeline {
    agent any

    environment {
        EC2_IP = "44.216.122.26"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'mern-stacks09233git',
                    url: 'https://github.com/kaviyarashugayu1997-maker/fullstack_project.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['mernstack-backend']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} << 'EOF'
set -e
mkdir -p /home/ubuntu/apps
cd /home/ubuntu/apps

if [ ! -d "fullstack_project" ]; then
    git clone https://github.com/kaviyarashugayu1997-maker/fullstack_project.git
fi

cd fullstack_project
git fetch origin
git checkout main
git pull origin main

cd backend

docker stop myapp || true
docker rm myapp || true 

docker build -t backend-image .
docker run -d -p 5001:5000 --name myapp backend-image

EOF
                    """
                }
            }
        }
    }

    post {
        success {
            echo "DEPLOYMENT SUCCESSFUL"
        }
        failure {
            echo "DEPLOYMENT FAILED"
        }
    }
}

